package ksr.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-11T21:46:22.762+05:30
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "KsrWebserviceService", 
                  wsdlLocation = "file:/E:/workspace%201/ksrwebservice/src/main/resources/KsrWebservice.wsdl",
                  targetNamespace = "http://service.ksr/") 
public class KsrWebserviceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ksr/", "KsrWebserviceService");
    public final static QName KsrWebservicePort = new QName("http://service.ksr/", "KsrWebservicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/workspace%201/ksrwebservice/src/main/resources/KsrWebservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KsrWebserviceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/workspace%201/ksrwebservice/src/main/resources/KsrWebservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KsrWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KsrWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KsrWebserviceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public KsrWebserviceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public KsrWebserviceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public KsrWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns KsrWebservice
     */
    @WebEndpoint(name = "KsrWebservicePort")
    public KsrWebservice getKsrWebservicePort() {
        return super.getPort(KsrWebservicePort, KsrWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KsrWebservice
     */
    @WebEndpoint(name = "KsrWebservicePort")
    public KsrWebservice getKsrWebservicePort(WebServiceFeature... features) {
        return super.getPort(KsrWebservicePort, KsrWebservice.class, features);
    }

}
